
import { DrugInfo } from '../types';

export const drugData: DrugInfo[] = [
  {
    name: 'AMIKACINA',
    presentation: 'Solución inyectable 100 mg/2 ml.',
    laboratory: 'Biosano, Vitalis',
    indications: 'Antibiótico de uso restringido para tratamiento de infecciones resistentes a otro aminoglucósido: Infecciones causadas por Bacilos Gram Negativos en trato respiratorio, SNC, piel y tejidos blandos, infecciones tracto urinario.',
    dose: '15- 20 mg/kg/dosis cada 24- 36 horas.',
    maxDose: 'Dosis individualizada en base a concentraciones plasmáticas del medicamento.',
    administrationRoute: 'Infusión ev',
    storage: 'Temperatura ambiente a no más de 30°C, protegido de la luz.',
    reconstitution: 'No requiere.',
    dilution: '10 mg/ml.',
    dilutionStandard: 'Extraer 1 ml de la ampolla (50 mg) y diluir con suero compatible hasta alcanzar un volumen final de 5 ml. Concentración final: 10 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%',
    stability: 'Usar y eliminar.',
    administrationSpeed: '30 minutos.',
    incompatibility: 'Ampicilina, Anfotericina B, Fenitoína, Dexametasona, Cloxacilina, Indometacina, Cotrimoxazol.',
    adverseEffects: 'Trastornos Auditivos: Ototoxicidad, pérdida de audición y equilibrio. Trastornos Renales: Nefrotoxicidad. Trastornos Neurológicos: Bloqueo neuromuscular.'
  },
  {
    name: 'AMPICILINA',
    presentation: 'Polvo para solución inyectable 500 mg.',
    laboratory: 'Libra, Pisa',
    indications: 'Antibiótico de amplio espectro útil en infecciones por Streptococo grupo B, Listeria Monocytogenes, Escherichia coli y especies susceptibles.',
    dose: 'Bacteriemias 100-150 mg/kg/día. Meningitis 300 mg/Kg/día',
    maxDose: '400 mg/Kg/día',
    administrationRoute: 'Bolo (dosis < 50 mg/Kg), Infusión ev (dosis ≥ 50 mg/Kg)',
    storage: 'No más de 25° C y protegido de la luz.',
    reconstitution: '5 ml de agua bidestilada.',
    dilution: 'No requiere',
    dilutionStandard: 'No aplica',
    compatibleIVFluids: 'Agua para inyectables, Cloruro de Sodio 0.9%, Suero glucosado 5% (más estable).',
    stability: 'Una vez reconstituida dura máximo 1 hora a temperatura ambiente, posterior a esto pierde su potencia.',
    administrationSpeed: 'Bolo: Entre 3 a 5 minutos. Infusión: al menos 30 minutos',
    incompatibility: 'Amikacina, Gentamicina, Hidralazina, Midazolam, Fluconazol.',
    adverseEffects: 'Trastornos Neurológicos: En dosis altas excitación del Sistema Nervioso Central y convulsiones. Trastornos Inmunológicos: Rash, urticaria y fiebre.'
  },
  {
    name: 'ANFOTERICINA B',
    presentation: 'Liofilizado para solución inyectable 50mg.',
    laboratory: 'Vitalis',
    indications: 'Tratamiento para micosis invasiva causada por hongos sensibles comúnmente Aspergillus, Candidas, Critococcus, o Zigomicetos',
    dose: '0.5- 1 mg/Kg cada 24 horas.',
    maxDose: '1,5 mg/kg/día',
    administrationRoute: 'Infusión ev',
    storage: 'Refrigerado, protegido de la luz.',
    reconstitution: '10 ml agua bidestilada',
    dilution: '0.1 mg/ml',
    dilutionStandard: 'Extraer 1 ml (5 mg) de la solución reconstituida y diluir con suero compatible hasta alcanzar un volumen final de 50 ml. Concentración final: 0,1 mg/ml',
    compatibleIVFluids: 'Suero Glucosado 5%.',
    stability: 'Reconstituido y diluido dura 24 horas a temperatura ambiente y 7 días refrigerado (2°C- 8°C)',
    administrationSpeed: '2-6 horas',
    incompatibility: 'No se recomienda su administración con otros medicamentos. No mezclar con Cloruro de Sodio 0,9%.',
    adverseEffects: 'Trastornos Inmunológicos: Fiebre, escalofríos. Trastornos Vasculares: Hipotensión. Trastornos Gastrointestinales: Náuseas. Trastornos Respiratorios: Taquipnea. Trastornos Renales: Nefrotoxicidad. Trastornos Sanguíneos: Anemia, trombocitopenia. Trastornos Metabólicos: Hipopotasemia.'
  },
  {
    name: 'CEFOTAXIMA',
    presentation: 'Polvo para solución inyectable 1 gr.',
    laboratory: 'BPH, Reyoung',
    indications: 'Meningitis neonatal, sepsis por BGN (E. coli, H. influenzae, Klebsiella, Pseudomonas), infección gonocócica diseminada',
    dose: '50 mg/kg/dosis cada 12-8-6 hrs',
    maxDose: '300 mg/kg/día, no exceder los 8 g/día',
    administrationRoute: 'Infusión ev',
    storage: 'Temperatura ambiente, protegido de la luz y humedad',
    reconstitution: '10 ml de agua bidestilada.',
    dilution: '40 mg/ml',
    dilutionStandard: 'Extraer 2 ml (200 mg) de la solución reconstituida y diluir con suero compatible hasta alcanzar un volumen final de 5 ml. Concentración final: 40 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0,9%, Suero Glucosado 5% y Suero Glucosado 10%.',
    stability: '24 horas a temperatura ambiente y 7 días bajo refrigeración',
    administrationSpeed: '20-30 min',
    incompatibility: 'Fluconazol y Vancomicina.',
    adverseEffects: 'Trastornos Gastrointestinales: Diarrea. Trastornos Inmunológicos: Rash. Trastornos Vasculares: Flebitis. Trastornos Sanguíneos: leucopenia, granulocitopenia, eosinofilia.'
  },
  {
    name: 'CIPROFLOXACINO',
    presentation: 'Solución inyectable 200mg/ 100 ml',
    laboratory: 'Fresenius Kabi',
    indications: 'Tratamiento de infecciones causadas por organismos sensibles demostrado por antibiograma (Ej. Infecciones del tracto respiratorio, tracto urinario, piel y tejido blando, óseas y articulares, infecciones quirúrgicas, etc)',
    dose: '<34 semanas: 7,5 mg/kg cada 12 horas. >34 semanas: 12,5 mg/kg cada 12 horas',
    maxDose: '1200 mg/día (dosis máxima de adulto)',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar a temperatura ambiente (< 25° C), protegido de la luz. No congelar.',
    reconstitution: 'No requiere',
    dilution: 'No requiere',
    dilutionStandard: 'No aplica',
    compatibleIVFluids: 'Cloruro de Sodio 0,9%, Suero glucosado al 5% y Suero Glucosado 10%.',
    stability: 'Se recomienda usar dentro de 24 horas, preferiblemente usar y eliminar.',
    administrationSpeed: '60 minutos.',
    incompatibility: 'Aminofilina, ampicilina/sulbactam, bicarbonato de sodio, cloxacilina, dexametasona, fenitoína, fosfato sódico, furosemida, heparina sódica, hidrocortisona, sulfato de magnesio, meropenem, metilprednisolona.',
    adverseEffects: 'Trastornos gastrointestinales: Náuseas, vómitos, diarrea, dolor abdominal. Trastornos inmunológicos: rash cutáneo, reacciones en sitio de. Trastornos respiratorios: dificultad respiratoria. Trastornos sanguíneos: eosinofilia, leucopenia, anemia. Trastornos neurológicos: alteraciones del SNC. Trastornos hepáticos: alteración pruebas hepáticas.',
    observations: 'No se recomienda su uso en lactantes, niños y adolescentes debido a reportes de artropatía. Preferir alternativas. Debido a su potente efecto venoirritante se recomienda administrar el medicamento en venas grandes. Dosis puede requerir de ajuste en pacientes con disfunción renal.'
  },
  {
    name: 'CLOXACILINA',
    presentation: 'Polvo para solución inyectable 500 mg',
    laboratory: 'DFM Pharma',
    indications: 'Infecciones causadas por gérmenes sensibles especialmente S. aureus meticilin-sensible',
    dose: '25 mg/Kg cada 6, 8 o 12horas (dosis dependiente de peso y edad postnatal)',
    maxDose: '8 g/día',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar a temperatura ambiente (<25°C)',
    reconstitution: '5ml de agua bidestilada',
    dilution: '50 mg/ml',
    dilutionStandard: 'Extraer 1 ml (100 mg) de la solución reconstituida y diluir con suero compatible hasta llegar a un volumen final de 2 ml. Concentración final: 50 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%.',
    stability: '24 hrs a temperatura ambiente y 48 horas bajo refrigeración (2-8° C)',
    administrationSpeed: '30-40 minutos',
    incompatibility: 'Amikacina, ciprofloxacino, diazepam, dobutamina, fenitoina, fosfato sódico, gentamicina, labetalol, lorazepam, midazolam, morfina, rocuronio, trimetorpim/sulfametoxazol (cotrimoxazol), vancomicina',
    adverseEffects: 'Trastorno Inmunológico: erupción cutánea, fiebre. Trastornos Gastrointestinales: diarrea, vómitos. Trastornos Sanguíneos: anemia, leucopenia. Trastornos Metabólicos: desequilibrio en los electrolitos sanguíneos. Trastornos Neurológicos: convulsiones. Trastornos Hepáticos: ictericia colestásica. Trastornos Renales: nefritis intersticial.'
  },
  {
    name: 'COTRIMOXAZOL (TRIMETOPRIM-SULFAMETOXAZOL)',
    presentation: 'Solución inyectable, para infusión intravenosa (trimetoprim 80 mg - sulfametoxazol 400 mg/ 5 ml)',
    laboratory: 'Roche, Unifarma',
    indications: 'Tratamiento y prevención de neumonía ocasionada por Pneumocystis jirovechi.',
    dose: 'En base a trimetoprim: 12 mg/Kg cada 12 hrs.',
    maxDose: '160 mg/ dosis',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar en envase original entre 15 y 25°C, evitar exposición a la luz.',
    reconstitution: 'No requiere.',
    dilution: '1,06 mg/ ml',
    dilutionStandard: 'Extraer 1 ml del frasco ampolla (16 mg) y diluir con suero compatible hasta alcanzar un volumen final de 15 ml. Concentración final: 1,06 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%, Suero glucosado 10%',
    stability: 'La solución diluida en suero glucosado 5% (1,06 mg/ml) es estable 2 horas a temperatura ambiente y protegida de la luz. Usar y eliminar.',
    administrationSpeed: '60-120 minutos.',
    incompatibility: 'Cloxacilina, Caspofungina, Fluconazol.',
    adverseEffects: 'Trastornos Gastrointestinales: Nauseas, Diarrea. Trastornos Sanguíneos: Anemia megaloblástica. Trastorno Metabólicos: Hiperpotasemia. Trastornos Vasculares: Tromboflebitis local en el sitio de inyección.',
    observations: 'Contiene etanol como excipiente (preservante), usar con precaución.'
  },
  {
    name: 'FLUCONAZOL',
    presentation: 'Solución inyectable 2mg/ml, 100 ml',
    laboratory: 'Fresenius Kabi',
    indications: 'Tratamiento de Candidiasis sistémica y meningitis criptocócica. Profilaxis de candidiasis en pacientes inmunocomprometidos.',
    dose: 'Profilaxis: 3mg/kg/dosis 2 veces por semana. Mantención: 6-12 mg/kg/dosis.',
    maxDose: '12 mg/kg/día, no exceder los 600 mg/día',
    administrationRoute: 'Infusión ev',
    storage: 'Temperatura menor a 30°C. No congelar.',
    reconstitution: 'No requiere.',
    dilution: 'No requiere.',
    dilutionStandard: 'No aplica',
    compatibleIVFluids: 'No aplica',
    stability: 'Una vez abierto dura 72 hrs.',
    administrationSpeed: '60-120 minutos',
    incompatibility: 'Ampicilina, Anfotericina B, Cefotaxima, Clindamicina, Furosemida, Gluconato de Calcio, Cotrimoxazol, Ceftazidima, Diazepam.',
    adverseEffects: 'Trastornos Hepáticos: Aumento de bilirrubina y transaminasas, colestasis. Otros: prolongación intervalo QT'
  },
  {
    name: 'GENTAMICINA',
    presentation: 'Solución inyectable, 80mg/2ml',
    laboratory: 'Sanderson, Vitalis',
    indications: 'Infecciones por BGN (Pseudomonas, Klebsiella, E. coli). Generalmente asociado a un betalactámico',
    dose: '5 mg/Kg cada 48, 36 o 24 horas (dependiendo de edad gestacional y edad postnatal)',
    maxDose: '',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar a temperatura ambiente y protegido de la luz. No congelar',
    reconstitution: 'No requiere.',
    dilution: '10 mg/ml',
    dilutionStandard: 'Extraer 2 ml (80 mg) del frasco ampolla y diluir con suero compatible hasta alcanzar un volumen final de 8 ml. Concentración final: 10 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero glucosado 5%.',
    stability: 'Usar y eliminar.',
    administrationSpeed: '30-120 minutos',
    incompatibility: 'Alopurinol, anfotericina B, ampicilina*, cefepime*, cefazolina*, clindamicina*, furosemida, heparina, indometacina, fenitoina, propofol. * Incompatibilidad solo en mezcla.',
    adverseEffects: 'Trastornos Neurológicos: Neurotoxicidad, bloqueo neuromuscular. Trastornos Auditivos: ototoxicidad. Trastornos Renales: nefrotoxicidad. Trastornos Respiratorios: depresión respiratoria. Trastornos Motores: parálisis muscular. Trastornos Inmunológicos: reacciones de hipersensibilidad. Trastornos Gastrointestinales: vómito, náuseas. Trastornos hepáticos.'
  },
  {
    name: 'MEROPENEM',
    presentation: 'Polvo para solución inyectable 500mg.',
    laboratory: 'DFM Pharma, Vitalis',
    indications: 'Antibiótico Betalactámico restringido al tratamiento de meningitis neumocócica y otras infecciones graves causadas por organismos gramnegativos susceptibles resistentes a otros antibióticos de amplio espectro, en especial Klebsiella pneumoniae productora de betalactamasa.',
    dose: 'Septicemia: 20 - 30 mg/kg/dosis cada 12 u 8 horas. Meningitis e Infecciones causadas por Pseudomonas: 40 mg/kg/dosis cada 8 horas.',
    maxDose: '120 mg/Kg/día, no exceder los 6 g/ día',
    administrationRoute: 'Infusión ev',
    storage: 'Temperatura menor a 25°C.',
    reconstitution: '10 ml de agua bidestilada',
    dilution: 'No requiere.',
    dilutionStandard: 'No aplica',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%, Suero Glucosado 10%.',
    stability: 'Reconstituido con Agua Bidestilada mantiene su potencia a temperatura ambiente generalmente un máximo de 2 horas y 12 horas refrigerado (entre +2°C-y+8°C).',
    administrationSpeed: '15-30 minutos.',
    incompatibility: 'Anfotericina B, Aciclovir, Ciprofloxacino, Bicarbonato de Sodio, Gluconato de Calcio.',
    adverseEffects: 'Trastornos Gastrointestinales: Diarrea, nausea, vómito, Colitis pseudomembranosa. Trastornos Inmunológicos: Erupción cutánea, mayor. Trastornos Vasculares: Flebitis. Trastornos Sanguíneos: Trombocitosis y eosinofilia',
    observations: '* El volumen de dilución puede variar de acuerdo al tiempo de infusión indicado. ** Consultar con químico farmacéutico posibilidad de usar esquema en infusión prolongada'
  },
  {
    name: 'METRONIDAZOL',
    presentation: 'Solución inyectable 500 mg/100 ml (0,5%)',
    laboratory: 'Fresenius Kabi, Sanderson',
    indications: 'Profilaxis de infecciones colónicas perioperatorias y en el tratamiento de infecciones bacterianas anaeróbicas, amebiasis y tricomoniasis.',
    dose: '7,5 mg/Kg cada 24, 12, 8 o 6 hrs (dosis depende de la edad postmenstrual)',
    maxDose: '4 g/día',
    administrationRoute: 'Infusión ev',
    storage: 'Temperatura ambiente (<30°C), protegido de la luz. No congelar',
    reconstitution: 'No requiere',
    dilution: 'No requiere',
    dilutionStandard: 'No aplica',
    compatibleIVFluids: 'Cloruro de Sodio 0,9% y Suero glucosado al 5%',
    stability: 'Algunos preparados requieren ser protegidos de la luz durante su administración. No contiene preservantes, se recomienda usar y eliminar.',
    administrationSpeed: '60 minutos',
    incompatibility: 'Anfotericina B, Filgrastim',
    adverseEffects: 'Trastornos Gastrointestinales: náuseas, diarrea. Trastornos Vasculares: tromboflebitis. Trastornos Neurológicos: neuropatía periférica, convulsiones. Trastornos Inmunológicos: rash. Trastornos Sanguíneos: leucopenia',
    observations: 'Requiere ajuste de dosis en pacientes con disfunción hepática severa. No usar equipo que contenga aluminio (ej. Agujas, cánulas, etc).'
  },
  {
    name: 'PENICILINA G SÓDICA (BENCILPENICILINA)',
    presentation: 'Polvo para solución inyectable 1.000.000 UI',
    laboratory: 'Improfar, Opko',
    indications: 'Tratamiento sífilis congénita. Otros microrganismos como gonococo y estreptococos.',
    dose: 'Bacteriemia y Sífilis Congénita: 50.000 UI/kg/dosis.',
    maxDose: '24.000.000 UI/día',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar a temperatura ambiente no más 30°C.',
    reconstitution: '5 ml de agua bidestilada.',
    dilution: '100.000 UI/ml.',
    dilutionStandard: 'Extraer 1 ml (200.000 UI) de la solución reconstituida y diluir con suero compatible hasta alcanzar un volumen final de 2 ml. Concentración final: 100.000 UI/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%.',
    stability: 'Reconstituida dura 24 horas a temperatura ambiente y 72 horas bajo refrigeración (2°-8°C).',
    administrationSpeed: 'Por infusión intermitente entre 15-30 minutos.',
    incompatibility: 'Aminofilina, Anfotericina B, Fenitoína, Fenobarbital.',
    adverseEffects: 'Trastornos Vasculares: Flebitis, tromboflebitis localizadas. Trastornos Neurológicos (dosis altas): Coma, mioclonías, convulsiones. Trastornos Gastrointestinales: Colitis Pseudomembranosa. Trastornos inmunológicos: Anafilaxis, hipersensibilidad (inmediata o retardada).',
    observations: 'Tener presente contenido de sodio entregado por administración (1.000.000 UI aportan 1,68 mEq sodio.'
  },
  {
    name: 'PIPERACILINA-TAZOBACTAM',
    presentation: 'Polvo liofilizado para solución inyectable Piperacilina 4 g, Tazobactam 0,5 g',
    laboratory: 'Wyeth',
    indications: 'Tratamiento de infecciones polimicrobianas severas en que se sospeche presencia de microorganismos aerobios y anaerobios',
    dose: '100 mg/kg/dosis cada 8 horas. 80 mg/Kg/dosis cada 6 o 4 horas. *dosificación en base a componente piperacilina',
    maxDose: '400 mg/kg/día, no exceder los 16 g de piperacilina por día',
    administrationRoute: 'Infusión ev',
    storage: 'A temperatura ambiente ≤ 30°C',
    reconstitution: '20 ml de suero compatible.',
    dilution: '50 mg/ml (en base a piperacilina)',
    dilutionStandard: 'Extraer 5 ml (1000 mg de piperacilina) de la solución reconstituida y diluir con suero compatible hasta alcanzar un volumen final de 20 ml. Concentración final: 50 mg/ml',
    compatibleIVFluids: 'Agua bidestilada, Cloruro de Sodio 0.9%, Suero Glucosado 5%.',
    stability: '48 horas refrigerado, 2 y 8°C. 24 horas a temperatura ambiente, 20-25°C',
    administrationSpeed: '30 minutos',
    incompatibility: 'Aciclovir, amikacina, amiodarona, anfotericina B, caspofungina, dobutamina, ganciclovir, gentamicina, tobramicina, vancomicina.',
    adverseEffects: 'Trastornos Sanguíneos: Leucopenia, neutropenia, anemia. Trastornos Gastrointestinales: diarrea, vómito. Trastornos Inmunológicos: erupción cutánea, hipersensibilidad. Trastornos Hepáticos: hiperbilirrubinemia. Elevación de ALT, AST. Trastornos Renales: elevación BUN y creatinina. Trastornos Vasculares: hipotensión, tromboflebitis'
  },
  {
    name: 'VANCOMICINA',
    presentation: 'Polvo liofilizado para solución inyectable 500 mg',
    laboratory: 'Teva',
    indications: 'En tratamiento de infecciones severas o graves causadas por cepas susceptibles de estafilococos meticilino resistentes. Efectivo en endocarditis estafilocócica.',
    dose: '15- 60 mg/kg/día',
    maxDose: 'Dosis individualizada en base a concentraciones plasmáticas del medicamento. No exceder dosis máxima de adultos: 4 g/día.',
    administrationRoute: 'Infusión ev',
    storage: 'Conservar a temperatura ambiente a no más de 30° C.',
    reconstitution: '10 ml de agua bidestilada.',
    dilution: '5 mg/ml',
    dilutionStandard: 'Extraer 1 ml (50 mg) de la solución reconstituida y diluir con suero compatible hasta alcanzar un volumen final de 10 ml. Concentración final: 5 mg/ml',
    compatibleIVFluids: 'Cloruro de Sodio 0.9%, Suero Glucosado 5%',
    stability: 'Reconstituido entre 2º C y 8º C no más de 14 días.',
    administrationSpeed: '60-120 minutos',
    incompatibility: 'Cefazolina, Cloxacilina, Heparina, Cotrimoxazol, Piperacilina-Tazobactam, Indometacina, Albumina 20%, Aminofilina, Anfotericina B, Furosemida.',
    adverseEffects: 'Trastornos Renales: Nefrotoxicidad. Trastornos Auditivos: Ototoxicidad, aumentadas en combinación con aminoglucosidos. Trastornos Vasculares: Hipotensión, Flebitis. Trastornos Inmunológicos: Rash cutáneo, que se resuelve al aumentar el tiempo de infusión. Trastornos Sanguíneos: Neutropenia, en tratamiento > 3 semanas.'
  }
];
